---
name: ðŸž Bug Report
description: Report a Reproducible Bug in the Current Release of this Website
labels: [ "type: bug" ]
assignees: "VKumar786"
body:
  - type: markdown
    attributes:
      value: >
        **Note:** This form is exclusively for reporting _reproducible bugs_ in the current Website deployment.

  - type: input
    attributes:
      label: Website Version
      description: Indicate the version of website you are currently running.
      placeholder: v1.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >
        When submitting a bug report for the website, it's essential to provide comprehensive step-by-step instructions for reproducing the issue on a clean installation. These instructions should be clear enough for someone else to follow effortlessly and must encompass configuration changes, and a complete accounting of the actions being taken. Remember, the goal is to ensure that the problem can be replicated precisely using the current stable release of the website.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Banner should be displayed upon first login.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Observed Behavior
      description: Describe what actually happened.
      placeholder: A TypeError exception was raised
    validations:
      required: true
