################################################################
# Dockerfile to build Wildfly container image for Jelastic
# Based on Centos 7
################################################################

#Jelastic Centos7 base image is used fo building
FROM jelasticdocker/jelastic-centos7-base:latest

LABEL maintainer="Jelastic,Inc"

ENV WILDFLY_VERSION 13.0.0.Final
ENV ADMIN_USER jelastic
ENV ADMIN_PASSWORD jelastic

#Installing OpenJDK8
RUN yum -y install java-1.8.0-openjdk-devel tar && yum -y update;
#Downloading and unpacking the Wildfly application server
RUN cd /opt && curl -O https://download.jboss.org/wildfly/${WILDFLY_VERSION}/wildfly-${WILDFLY_VERSION}.tar.gz \
&& $(which tar) xf wildfly-${WILDFLY_VERSION}.tar.gz \
&& rm wildfly-${WILDFLY_VERSION}.tar.gz
#Creating symbolic lynk for easier access to server directory
RUN ln -s /opt/wildfly-$WILDFLY_VERSION /opt/wildfly

#Setting the configuration values for Wildfly
RUN echo -en "JAVA_HOME=\"/usr/lib/jvm/java\""'\n'\
"JBOSS_HOME=\"/opt/wildfly\""'\n'\
"JBOSS_USER=wildfly"'\n'\
"JBOSS_MODE=standalone"'\n'\
"JBOSS_CONFIG=standalone.xml"'\n'\
"STARTUP_WAIT=60"'\n'\
"SHUTDOWN_WAIT=60"'\n'\
"JBOSS_CONSOLE_LOG=\"/var/log/wildfly/console.log\""'\n'\
"JBOSS_OPTS=\"-b 0.0.0.0 -bmanagement=0.0.0.0 -Djboss.management.http.port=4949 -Djboss.management.https.port=4848\"" >> /etc/default/wildfly

#Copying the Wildfly init script to /etc/init.d/ directory
RUN wget https://raw.githubusercontent.com/wildfly/wildfly-core/master/core-feature-pack/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-redhat.sh -O /etc/rc.d/init.d/wildfly; \
    sed -i "/# Source function library/a\SYSTEMCTL_SKIP_REDIRECT=1" /etc/init.d/wildfly; chmod +x /etc/init.d/wildfly;

#Adding application user, changing ownerships to this user, setting Wildfly to start on system startup
RUN chkconfig --add wildfly; chkconfig wildfly on; mkdir -p /var/log/wildfly; adduser wildfly; \
    chown -R wildfly:wildfly /opt/wildfly-$WILDFLY_VERSION /opt/wildfly /var/log/wildfly;

#Adding the user for Wildfly admin console
RUN /opt/wildfly/bin/add-user.sh --user $ADMIN_USER --password $ADMIN_PASSWORD --silent --enable

#Setting the right redirect for admin panel link of the homepage
RUN sed -i "s/<a href=\"\/console\">/<a href=\"\/console\" onclick=\"javascript:event.target.port=4949;event.target.protocol=\'http:\';\">/" /opt/wildfly/welcome-content/index.html

#Adding locale settings
RUN  localedef -i en_US -f UTF-8 en_US.UTF-8

#Listening to the required ports at the runtime
EXPOSE 22 80 443 8080 8743 9990 9993 8009 4848 4949

#Setting the entrypoint
ENTRYPOINT ["/bin/bash"]
